---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetserver
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: puppetserver
  template:
    metadata:
      labels:
        app: puppetserver
    spec:
      restartPolicy: Always
      containers:
      - name: puppetserver
        image: quay.io/openinfra/puppetserver:v7.9.2-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8140
          protocol: TCP
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /healthz
        #     port: 8140
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
        volumeMounts:
        - name: puppetca-tls
          mountPath: "/etc/puppetlabs/puppetserver/ca-tls"
          readOnly: true
      volumes:
        - name: puppetca-tls
          secret:
            secretName: puppetca-tls
            optional: false

