apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: puppetca-tls
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: kv/k1/kube-namespace/jeff/puppetca-tls
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: core-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: puppetca-tls
